// Objective-C API for talking to p2p/core Go package.
//   gobind -lang=objc p2p/core
//
// File is generated by gobind. Do not edit.

#ifndef __Core_H__
#define __Core_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class CoreCore;

@interface CoreCore : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)addrStr username:(NSString* _Nullable)username;
- (void)sendMessage:(NSString* _Nullable)text;
- (void)setPeerID:(NSString* _Nullable)peerID;
- (BOOL)start:(NSError* _Nullable* _Nullable)error;
- (void)stop;
@end

FOUNDATION_EXPORT CoreCore* _Nullable CoreNewCore(NSString* _Nullable addrStr, NSString* _Nullable username);

#endif
